image: alpine 

stages:
    - deploy_dev
    - test_dev
    - deploy_tst
    - test_tst
    - deploy_prd
    - test_prd
    - parallel_job_test
    
before_script:
#    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
    - apk update
    - apk add python3
    - apk add nodejs


dev_app_deploy:
    stage: deploy_dev
    script:
        - python3 helloworld.py
    environment:
        name: Testing
    only:  
        - master

dev_regression_test:
    stage: test_dev
    script:
        - which nodejs
    environment:
        name: Development
    when: on_success
    only: 
        - master

tst_app_deploy:
    stage: deploy_tst
    script:
        - which nodejs
    when: manual
    environment:
        name: Testing
    allow_failure: false
    only: 
        - master
    
tst_regression_test:
    stage: test_tst
    script:
        - which nodejs
    when: on_success
    environment:
        name: Testing
    only: 
        - master
    
prd_app_deploy:
    stage: deploy_prd
    script:
        - which nodejs
    environment:
        name: Production
    when: manual
    allow_failure: false
    only: 
        - master
    
prd_regression_test:
    stage: test_prd
    script:
        - which nodejs
    environment:
        name: Production
    when: on_success
    only: 
        - master

parallel_test_job_1:
    stage: parallel_job_test
    script:
        - which nodejs
    environment:
        name: Production
    when: on_success
    only: 
        - master
        
parallel_test_job_2:
    stage: parallel_job_test
    script:
        - which nodejs
    environment:
        name: Production
    when: on_success
    only: 
        - master