stages:
    - deploy_dev
    - deploy_tst
    - deploy_prd
    - test_dev
    - test_tst
    - test_prd
    
before_script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

dev_app_deploy:
    stage: deploy_dev
    script:
        - bundle exec rubocop

dev_regression_test:
    stage: test_dev
    script:
        - bundle exec rspec

tst_app_deploy:
    stage: deploy_tst
    script:
        - bundle exec rubocop

tst_regression_test:
    stage: test_tst
    script:
        - bundle exec rspec
prd_app_deploy:
    stage: deploy_prd
    script:
        - bundle exec rubocop

prd_regression_test:
    stage: test_prd
    script:
        - bundle exec rspec