stages:
    - deploy_dev
    - deploy_tst
    - deploy_prd
    - test_dev
    - test_tst
    - test_prd
    
before_script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs


dev_app_deploy:
    stage: deploy_dev
    script:
        - python helloworld.py
    only:  
        - master

dev_regression_test:
    stage: test_dev
    script:
        - which nodejs
    only: 
        - master

tst_app_deploy:
    stage: deploy_tst
    script:
        - which nodejs
    when: manual
    only: 
        - master
    
tst_regression_test:
    stage: test_tst
    script:
        - which nodejs
    only: 
        - master
    
prd_app_deploy:
    stage: deploy_prd
    script:
        - which nodejs
    when: manual
    only: 
        - master
    
prd_regression_test:
    stage: test_prd
    script:
        - which nodejs
    only: 
        - master